/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Take control of all pages immediately
self.skipWaiting();
clientsClaim();

// Handle notification clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  const data = event.notification.data;

  if (event.action === 'stop') {
    // Send message to all clients to stop training
    event.waitUntil(
      self.clients.matchAll({ type: 'window' }).then((clients) => {
        clients.forEach((client) => {
          client.postMessage({
            type: 'stop-training',
            trainingId: data.trainingId
          });
        });
      })
    );
  } else {
    // Open or focus the app
    event.waitUntil(
      self.clients
        .matchAll({ type: 'window', includeUncontrolled: true })
        .then((clientList) => {
          // Try to find an already open window
          for (const client of clientList) {
            if ('focus' in client) {
              return client.focus();
            }
          }
          // If no window is open, open a new one
          if (self.clients.openWindow) {
            return self.clients.openWindow(data.url || '/');
          }
        })
    );
  }
});

// Listen for messages from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
