/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Take control of all pages immediately
self.skipWaiting();
clientsClaim();

// Handle notification clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  const urlWithHash = '/#from-training-notification';

  // Open or focus the app
  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Try to find an already open window
        for (const client of clientList) {
          if ('focus' in client) {
            // Navigate to URL with hash to signal notification click
            if ('navigate' in client) {
              client.navigate(urlWithHash);
            }
            return client.focus();
          }
        }
        // If no window is open, open a new one with the hash
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlWithHash);
        }
      })
  );
});

// Listen for messages from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
